### ISSUE TITLE
Multiple Submit buttons appear if down button is pressed multiple times after survey reaches the end.

### ISSUE THREAD

**Issue by Joskef** [VincentII/Praxis-Survey#2]
![image](https://cloud.githubusercontent.com/assets/17984538/22727128/2663b28a-ee12-11e6-8778-b1c02f4b15ec.png)

To duplicate this bug, the user is required to answer the whole survey and once the last question is provided, the user will press the down button again, prompting multiple submit buttons to appear each time the down button is pressed again.

**Comment by VincentII** [comment]
FIXED by Dante

**Comment by Joskef** [comment]
Issue still persists, but this time it creates multiple cards for submit.

How to reproduce.

1. Finish the survey up until submit button appears.
2. Do not submit.
3. Reanswer any item.
4. Press down button again

Another card for submit shall appear which does the same thing as the old submit button from earlier.

**Comment by Joskef** [comment]
Problem has been fixed.
